version: "3.8"

services:
  loki:
    image: grafana/loki:2.9.4
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/custom-config.yaml 
    volumes:
      - ./loki-config.yaml:/etc/loki/custom-config.yaml
      - lokidata:/loki

  grafana:
    image: grafana/grafana:10.2.3
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - loki
    volumes:
      - grafanadata:/var/lib/grafana

volumes:
  lokidata:
  grafanadata: